name: Create QubesOS RPMs

on:
  pull_request:
  push:
    tags:
      - '*'

jobs:
  antievilmaid:
    uses: TrenchBoot/.github/.github/workflows/qubes-dom0-packagev2.yml@master
    with:
      qubes-component: 'antievilmaid'
